### ISSUE TITLE
Dockerfile: Jupyterlab installation incorrect

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/neuro-base-environment#24]
Run command:
`jupyter lab --debug --allow-root --dev-mode`
Output:
```
[D 13:05:28.951 LabApp] > node /usr/local/lib/python3.6/dist-packages/jupyterlab/staging/yarn.js check --verify-tree
[W 13:05:28.951 LabApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1618, in init_server_extensions
        func(self)
      File "/usr/local/lib/python3.6/dist-packages/jupyterlab/extension.py", line 171, in load_jupyter_server_extension
        ensure_dev(logger)
      File "/usr/local/lib/python3.6/dist-packages/jupyterlab/commands.py", line 206, in ensure_dev
        if ensure_node_modules(parent, logger) or not osp.exists(target):
      File "/usr/local/lib/python3.6/dist-packages/jupyterlab/commands.py", line 185, in ensure_node_modules
        yarn_proc = ProgressProcess(['node', YARN_PATH, 'check', '--verify-tree'], cwd=cwd, logger=logger)
      File "/usr/local/lib/python3.6/dist-packages/jupyterlab/commands.py", line 80, in __init__
        universal_newlines=True,
      File "/usr/local/lib/python3.6/dist-packages/jupyterlab_server/process.py", line 164, in _create_process
        cmd[0] = which(cmd[0], kwargs.get('env'))
      File "/usr/local/lib/python3.6/dist-packages/jupyterlab_server/process.py", line 59, in which
        raise ValueError(msg)
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
```

Also tests failing:
```
[.] Running command: `bash -c "jlpm --version"`
Traceback (most recent call last):
  File "/usr/local/bin/jlpm", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyterlab/jlpmapp.py", line 43, in main
    execvp('node', ['node', YARN_PATH] + argv)
  File "/usr/local/lib/python3.6/dist-packages/jupyterlab/jlpmapp.py", line 24, in execvp
    cmd = which(cmd)
  File "/usr/local/lib/python3.6/dist-packages/jupyterlab_server/process.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
[-] Error <class 'AssertionError'>: non-zero exit code: 1
[.] Running command: `bash -c "jlpm versions"`
Traceback (most recent call last):
  File "/usr/local/bin/jlpm", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyterlab/jlpmapp.py", line 43, in main
    execvp('node', ['node', YARN_PATH] + argv)
  File "/usr/local/lib/python3.6/dist-packages/jupyterlab/jlpmapp.py", line 24, in execvp
    cmd = which(cmd)
  File "/usr/local/lib/python3.6/dist-packages/jupyterlab_server/process.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
```
Note: `pip install -U nodejs` won't help:
```
# pip install -U nodejs
Requirement already up-to-date: nodejs in /usr/local/lib/python3.6/dist-packages (0.1.1)
Requirement already satisfied, skipping upgrade: optional-django==0.1.0 in /usr/local/lib/python3.6/dist-packages (from nodejs) (0.1.0)
```
Somehow it installs version 0.1.1, but  required.

**Comment by ayushkovskiy** [comment]
fixed, tests are present
